name = "DualScreen"
version = 4
copyright = ""
description = "Moves UI elements to one screen when using split screen. Used with the game windowed and stretched across two screens."
author = "CodingSquirrel"
url = ""
uid = "e8b4bc13-7c0d-4560-8c38-431d3314e9d9"
exclusive = false
ui_only =true
conflicts = {  }